# Generated by Django 5.1.3 on 2024-12-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_pastevents_upcomingtourdates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastevents',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
