# Generated by Django 5.1.3 on 2024-12-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_upcomingtourdates_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('misc', 'Misc'), ('clothing', 'Clothing'), ('ticket', 'Ticket')], max_length=200, null=True),
        ),
    ]
