# Generated by Django 5.1.3 on 2025-02-03 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('ticket', 'Ticket'), ('clothing', 'Clothing'), ('misc', 'Misc'), ('album', 'Album')], max_length=200, null=True),
        ),
    ]
